// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-conversations.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-conversations.ts
var list_conversations_default = defineTool({
  name: "list_conversations",
  title: "List conversations",
  description: "List the signed-in user's chat conversations, newest first.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).optional().describe("Max conversations to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("conversations").select("id, title, created_at, updated_at").order("updated_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { conversations: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-conversation.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_conversation_default = defineTool2({
  name: "get_conversation",
  title: "Get conversation messages",
  description: "Read all messages in one of the signed-in user's conversations, oldest first.",
  inputSchema: {
    conversation_id: z2.string().describe("The conversation id, from list_conversations.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ conversation_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: conversation, error: convError } = await supabase.from("conversations").select("id, title, created_at, updated_at").eq("id", conversation_id).maybeSingle();
    if (convError) return { content: [{ type: "text", text: convError.message }], isError: true };
    if (!conversation) {
      return { content: [{ type: "text", text: "Conversation not found" }], isError: true };
    }
    const { data: messages, error } = await supabase.from("messages").select("id, role, content, created_at").eq("conversation_id", conversation_id).order("created_at", { ascending: true });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const payload = { conversation, messages: messages ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/search-messages.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var search_messages_default = defineTool3({
  name: "search_messages",
  title: "Search messages",
  description: "Search the signed-in user's chat messages for a text fragment.",
  inputSchema: {
    query: z3.string().min(1).describe("Text to search for inside message content."),
    limit: z3.number().int().min(1).max(100).optional().describe("Max matches to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const escaped = query.replace(/[%_]/g, (m) => `\\${m}`);
    const { data, error } = await supabase.from("messages").select("id, conversation_id, role, content, created_at").ilike("content", `%${escaped}%`).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { matches: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-conversation.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var create_conversation_default = defineTool4({
  name: "create_conversation",
  title: "Create conversation",
  description: "Create a new chat conversation for the signed-in user, optionally with a first message.",
  inputSchema: {
    title: z4.string().trim().min(1).describe("Title for the new conversation."),
    first_message: z4.string().trim().min(1).optional().describe("Optional first user message to store.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ title, first_message }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: conversation, error } = await supabase.from("conversations").insert({ user_id: ctx.getUserId(), title }).select("id, title, created_at, updated_at").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (first_message) {
      const { error: msgError } = await supabase.from("messages").insert({ conversation_id: conversation.id, role: "user", content: first_message });
      if (msgError) return { content: [{ type: "text", text: msgError.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(conversation) }],
      structuredContent: { conversation }
    };
  }
});

// src/lib/mcp/tools/delete-conversation.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var delete_conversation_default = defineTool5({
  name: "delete_conversation",
  title: "Delete conversation",
  description: "Permanently delete one of the signed-in user's conversations and its messages.",
  inputSchema: {
    conversation_id: z5.string().describe("The conversation id to delete.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false },
  handler: async ({ conversation_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("conversations").delete().eq("id", conversation_id).select("id");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data || data.length === 0) {
      return { content: [{ type: "text", text: "Conversation not found" }], isError: true };
    }
    return {
      content: [{ type: "text", text: `Deleted conversation ${conversation_id}` }],
      structuredContent: { deleted_id: conversation_id }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "acmbznvuknvraivyhjvb";
var mcp_default = defineMcp({
  name: "chat-assistant",
  title: "Chat Assistant",
  version: "0.1.0",
  instructions: "Tools for the Chat Assistant app. Use `list_conversations` to browse the signed-in user's chat conversations, `get_conversation` to read a conversation's messages, `search_messages` to find past messages, `create_conversation` to start a new one, and `delete_conversation` to remove one.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_conversations_default,
    get_conversation_default,
    search_messages_default,
    create_conversation_default,
    delete_conversation_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
